### PR TITLE
Make unused release_namespace parameter as optional

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Modules modified -
* helm_plugin
* helm_plugin_info

Fixes: #357

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/357_helm_plugin.yml
plugins/modules/helm_plugin.py
plugins/modules/helm_plugin_info.py

### CODE REVIEW

**Comment by gravesm** [comment]
I'm fine with the change, but I wonder if it might be better to push this to 2.0 since it will break any existing playbooks using these modules? Maybe we should remove the `required` attribute of this parameter for 1.2, which would fix the reported bug, and then merge this change in 2.0?

**Comment by Akasurde** [comment]
Make sense to me.

**Comment by tima** [comment]
I agree with what @gravesm [said](https://github.com/ansible-collections/community.kubernetes/pull/358#issuecomment-771625071).

**Review by tima — APPROVED** [review]
I agree with making this optional in 1.2 and slating it for removal in 2.0.

**Pull request merged**
