### PR TITLE
Fix default configuration getter in client v12.0.0

### LINKED ISSUE #273: regression caused by kubernetes==12.0.0
##### SUMMARY
Since running: sudo pip install kubernetes --upgrade I'm getting an error when trying to use 
community.kubernetes  collection 

please see below

This was reported https://github.com/kubernetes-client/python/issues/1284

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]

```

##### CONFIGURATION

```paste below
no applicable
```

##### OS / ENVIRONMENT

fedora 32

##### STEPS TO REPRODUCE

run 
sudo pip install kubernetes --upgrade

```yaml
```

##### EXPECTED RESULTS

working as usual

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0569d1f250>: Failed to establish a new connection: [Errno 111] Connection refused'))
fatal: [throwaway]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
        conn = connection.create_connection(
      File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
        raise err
      File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib64/python3.8/http/client.py", line 1255, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib64/python3.8/http/client.py", line 1301, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib64/python3.8/http/client.py", line 1250, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib64/python3.8/http/client.py", line 1010, in _send_output
        self.send(msg)
      File "/usr/lib64/python3.8/http/client.py", line 950, in send
        self.connect()
      File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
        conn = self._new_conn()
      File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
        raise NewConnectionError(
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0569d1f250>: Failed to establish a new connection: [Errno 111] Connection refused
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_k8s_payload_w31qom08/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py", line 281, in <module>
      File "/tmp/ansible_k8s_payload_w31qom08/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py", line 277, in main
      File "/tmp/ansible_k8s_payload_w31qom08/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py", line 171, in execute_module
      File "/tmp/ansible_k8s_payload_w31qom08/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py", line 200, in get_api_client
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/client.py", line 71, in __init__
        self.__discoverer = discoverer(self, cache_file)
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/discovery.py", line 259, in __init__
        Discoverer.__init__(self, client, cache_file)
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/discovery.py", line 31, in __init__
        self.__init_cache()
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/discovery.py", line 78, in __init_cache
        self._load_server_info()
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/discovery.py", line 158, in _load_server_info
        'kubernetes': self.client.request('get', '/version', serializer=just_json)
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/client.py", line 42, in inner
        resp = func(self, *args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/openshift/dynamic/client.py", line 235, in request
        return self.client.call_api(
      File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
        return self.__call_api(resource_path, method,
      File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
        response_data = self.request(
      File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
        return self.rest_client.GET(url,
      File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
        return self.request("GET", url,
      File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
        r = self.pool_manager.request(method, url,
      File "/usr/lib/python3.8/site-packages/urllib3/request.py", line 75, in request
        return self.request_encode_url(
      File "/usr/lib/python3.8/site-packages/urllib3/request.py", line 97, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "/usr/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
        return self.urlopen(
      File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
        return self.urlopen(
      File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
        return self.urlopen(
      File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
        retries = retries.increment(
      File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0569d1f250>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### PR DESCRIPTION
**Pull request by jaydesl**
##### SUMMARY
Use get_default_copy() to load the default configuration. Fixes #273 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
k8s module

##### ADDITIONAL INFORMATION
See also kubernetes-client/python#1284

### CODE REVIEW

**Review by geerlingguy — APPROVED** [review]

**Review by Akasurde — CHANGES_REQUESTED** [review]
@jaydesl Change looks good to me. Could you please add a test for this change ?

**Comment by fabianvf** [comment]
Yep, looks good to me once there's a test

**Comment by jaydesl** [comment]
Thoughts on this as a test?

**Review by geerlingguy — APPROVED** [review]

**Review by fabianvf — APPROVED** [review]

**Comment by Akasurde** [comment]
@jaydesl Thanks for adding test and fix.

**Pull request merged**
