### PR TITLE
fix downstream ci job naming

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <admiller@redhat.com>

##### SUMMARY

fix downstream ci job naming

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

.github/workflows/ci.yml

### CODE REVIEW

**Comment by geerlingguy** [comment]
CI tests are failing without this patch, can't believe I didn't catch this before merging the earlier PR... oops!

Once this passes we can merge.

**Comment by geerlingguy** [comment]
Looks like downstream-sanity is failing:

```
ERROR: Found 5 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/helm.py:0:0: parameter-type-not-in-doc: Argument 'kube_context' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/helm.py:0:0: parameter-type-not-in-doc: Argument 'kubeconfig_path' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/helm_info.py:0:0: parameter-type-not-in-doc: Argument 'kube_context' in argument_spec defines type as 'str' but documentation doesn't define type
ERROR: plugins/modules/helm_info.py:0:0: parameter-type-not-in-doc: Argument 'kubeconfig_path' in argument_spec defines type as 'path' but documentation doesn't define type
ERROR: plugins/modules/k8s_service.py:0:0: parameter-type-not-in-doc: Argument 'resource_definition' in argument_spec defines type as <function list_dict_str at 0x7fe90b45c048> but documentation doesn't define type
```

**Comment by maxamillion** [comment]
That test failure is interesting because the entire `tests` directory ends up in the downstream temporary builddir which includes the `./tests/sanity/ignore-2.9.txt` which should handle this. I'll dig in.

**Comment by maxamillion** [comment]
> That test failure is interesting because the entire `tests` directory ends up in the downstream temporary builddir which includes the `./tests/sanity/ignore-2.9.txt` which should handle this. I'll dig in.

Nevermind, I was on the wrong branch ... I accidentally fixed it in a different branch and didn't realize my mistake.

**Comment by geerlingguy** [comment]
@maxamillion haha, now the main sanity test is failing!

**Comment by maxamillion** [comment]
@geerlingguy I think something is wrong with GitHub actions, it doesn't look like it's pulling in the latest changes associated with this PR because it's complaining about a line in a file that no longer exists as per my latest commit ... any ideas?

**Comment by geerlingguy** [comment]
@maxamillion - Looking at the logs it's grabbing:

```
commit a2ac8b05f9d999bafcfe95f222a5d29fcc1a13f1
Author: Adam Miller <admiller@redhat.com>
Date:   Fri Aug 28 14:52:08 2020 +0000

    Merge 8e3a821b45291c0acca87c7f534bdcb5759732c1 into e9d8bf703bcb9bced1ae327d99be99e907d7d83a
```

**Comment by geerlingguy** [comment]
It is weird, though, because as you mention: https://github.com/ansible-collections/community.kubernetes/blob/8e3a821b45291c0acca87c7f534bdcb5759732c1/tests/sanity/ignore-2.11.txt — that doesn't have those lines in it.

So... can you either force push a rebase, or maybe close this PR and open a new one? Probably some weird GitHub Actions caching issue we've hit.

**Pull request closed without merging**
