### PR TITLE
Add test for openshift apply bug

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY
Add a failing test under openshift 0.11.0

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
k8s/raw

### CODE REVIEW

**Comment by willthames** [comment]
Ready to merge once https://github.com/openshift/openshift-restclient-python/pull/362 is merged and released

**Comment by willthames** [comment]
The test failures here are nothing to do with my code

**Comment by geerlingguy** [comment]
@willthames can you rebase on master? The pytest issue has been fixed.

**Comment by willthames** [comment]
@geerlingguy done

**Comment by geerlingguy** [comment]
@willthames - And of course quay.io is down currently 🤷‍♂️ — I'll try to rerun the tests after things are back up.

**Comment by geerlingguy** [comment]
It seems like tests are passing here, even if they're not passing on the main repo currently :-/ See https://github.com/ansible-collections/community.kubernetes/issues/104

**Pull request merged**
