### PR TITLE
k8s_scale fixes

### PR DESCRIPTION
**Pull request by willthames**
##### SUMMARY
Fix scale wait and add tests
    
Move wait logic out of raw and into common and use that
logic in scale
    
Fix a few broken wait condition cases highlighted by scaling
up and down
    
Move scale-related tests into dedicated test task file
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
k8s_scale
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by willthames** [comment]
Based on #35 - merge that one first

**Comment by geerlingguy** [comment]
Latest test is giving:

```
Failed to apply object: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure",
"message":"Service "apply-svc" is invalid: spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'"
```

...which is weird, because it seems like `type` is set to `NodePort`...?

**Comment by willthames** [comment]
@geerlingguy the bit where it was failing was in adding a port to an existing service, and also setting NodePort at the same time (I suspect I mis-merged two separate changes at some point) - just need to be consistently all NodePorts or all ClusterIPs. I've changed it to the latter.

**Comment by geerlingguy** [comment]
Now this is failing with the same thing mentioned in #104 — 

```
    TASK [Check that deployment wait worked] ***************************************
    task path: /home/runner/work/community.kubernetes/community.kubernetes/ansible_collections/community/kubernetes/molecule/default/tasks/waiter.yml:247
fatal: [localhost]: FAILED! => {
    "assertion": "updated_deploy_pods.resources[0].spec.containers[0].image.endswith(\":2\")",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
    Read vars_file 'vars/main.yml'
```

**Comment by willthames** [comment]
Yeah, there's definitely a race condition, not 100% sure on the best course of action - Kubernetes is doing the right thing, the tests are doing the right thing, just perhaps too soon.

I might just have to improve the filters to ignore the unready pod where its container has terminated but the pod is still not in terminating state (that bit is weird)

**Comment by geerlingguy** [comment]
Merging—it also seems to fix the instability with our CI tests, so I can stop getting nightly fail notifications from the scheduled CI run :)

**Pull request merged**
